services:
  db:
    image: mariadb:latest # Change from mysql:latest to mariadb:latest
    restart: always
    container_name: wfpdb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword # Change MYSQL_ to MARIADB_
      MARIADB_DATABASE: wfpdb
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      TZ: Asia/Bangkok
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./.sql:/docker-entrypoint-initdb.d/.sql
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "8005:3306"
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

volumes:
  mysql_data:
