services:
  db:
    image: mysql:latest
    restart: always
    container_name: wfpdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wfpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Bangkok
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./.sql:/docker-entrypoint-initdb.d/.sql
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "8005:3306"
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

volumes:
  mysql_data: 